sudo : required

services:
  - docker

before_install: 
  - docker build -t  ahmedjerid/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true ahmedjerid/react-test npm test

after_success: 
  - docker build -t jeridahmed/multi-client ./client 
  - docker build -t jeridahmed/multi-nginx ./nginx 
  - docker build -t jeridahmed/multi-server ./server 
  - docker build -t jeridahmed/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push jeridahmed/multi-client
  - docker push jeridahmed/multi-server
  - docker push jeridahmed/multi-worker
  - docker push jeridahmed/multi-nginx
